defaults: &defaults
  blog_name: "Bob's Blog"
  blog_description: "All the news that's fit to print."

development:
  <<: *defaults
  host: "localhost:3000"

test:
  <<: *defaults
  host: "localhost:3000"

production:
  <<: *defaults
  host: "blog.livoras.com"
